version: "3.9"

services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5431:5432
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  migration:
    build: .
    command: yarn typeorm migration:run -d src/data-source
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy

  api:
    container_name: api
    build: .
    command: yarn dev 0.0.0.0:3000
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    volumes:
      - .:/app
